# Build workflow for GitHub actions

name: Build & test

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
    
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
  
        - name: Setup NodeJS
          uses: actions/setup-node@v3
          with:
            node-version: 'latest'

        - name: Install NPM packages
          run: npm install src/FsiCAD.Webpack/

        - name: Build wwwroot assets
          run: npm run --prefix src/FsiCAD.Webpack build
        
        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '7.0.x'

        - name: Restore packages
          run: dotnet restore src/FsiCAD.sln

        - name: Build
          run: dotnet build --no-restore src/FsiCAD.sln
          
        - name: Test
          run: dotnet test --no-build --verbosity normal src/FsiCAD.sln